services:
  web:
    image: nginx
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./webroot:/etc/nginx/html

  beispiel1:
    image: nginx
    container_name: beispiel1
    ports:
      - "7001:80"
    volumes:
      - ./nginx1.conf:/etc/nginx/conf.d/default.conf
      - ./webroot/beispiel-1:/etc/nginx/html

  beispiel2:
    image: nginx
    container_name: beispiel2
    ports:
      - "7002:80"
    volumes:
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf
      - ./webroot/beispiel-2:/etc/nginx/html

  ftp:
    image: garethflowers/ftp-server
    container_name: ftp
    environment:
      FTP_PASS: $FTP_PASS
      FTP_USER: user
    ports:
      - 20-21:20-21/tcp
      - 40000-40009:40000-40009/tcp
    volumes:
      - /ftproot:/home/user
